### PR TITLE
Update pkgs.db

### PR DESCRIPTION
**Pull request by docteurmicro50**
firmware 1.4.1 update, I don't have the direct download link, anybody can help me and explain how to obtain this direct link download on cisco website?

### CODE REVIEW

**Comment by docteurmicro50** [comment]
Please also rename the name of the plugin repository : spa100-1.3.5p -> spa100-1.4.1

**Comment by sboily** [comment]
Hello, why did you open many PR ? Maybe it would be simple if you open one PR for SPA, one for yealink. The best is fork the project, using a git client with your branches and create PR.

**Comment by docteurmicro50** [comment]
Hi Sylvain, sorry I didn't find how to manage this fork from the github website.
I'll try to do that next time.

**Comment by pcadottemichaud** [comment]
Merged in the following pull request: https://github.com/xivo-pbx/xivo-provd-plugins/pull/27

**Pull request closed without merging**
